import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { notFound } from "next/navigation";
import { NextResponse } from "next/server";

/**
 * Generated by AgentSurface. Do not edit directly unless ownership is transferred.
 * Source model: .agentsurface/model/routes.json
 *
 * Serves AgentSurface-generated Markdown alternates. Reached only via the *.md
 * rewrite in middleware.ts — a bare top-level "/<path>.md" route would otherwise
 * collide with the existing [lang] dynamic segment (Next.js resolves that single
 * dynamic segment before any catch-all for a single path segment).
 */
export async function GET(_request: Request, { params }: { params: Promise<{ agentsurfaceSlug: string[] }> }) {
  const { agentsurfaceSlug } = await params;
  const slugPath = agentsurfaceSlug.join("/");

  if (!slugPath.endsWith(".md")) {
    notFound();
  }

  const withoutExt = slugPath.slice(0, -3);
  const relPath = withoutExt === "" || withoutExt === "index" ? "index" : withoutExt;
  const generatedFile = join(process.cwd(), ".agentsurface", "generated", "pages", `${relPath}.md`);

  if (!existsSync(generatedFile)) {
    notFound();
  }

  const content = readFileSync(generatedFile, "utf-8");
  return new NextResponse(content, {
    status: 200,
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
}
